# Deploy Load Balancer Service
apiVersion: v1
kind: Service
metadata:
  name: aj-loadbalancer
  labels:
    app: app
spec:
  selector:
    app: nginx
    env: dev
  type: LoadBalancer
  ports:
  - port: 80
    nodePort: 31000
    targetPort: 80
